dist: focal

script:
  - lsb_release -a > ubuntu_version.txt
  - apt list --installed > installed_packages.txt
  - cat ubuntu_version.txt
  - cat installed_packages.txt

after_success:
  - git config --global user.name "Travis CI"
  - git config --global user.email "your-email@example.com"
  - git clone https://$GITHUB_TOKEN@github.com/kamildevtactics/travis_build_test.git
  - cd travis_build_test
  - cp ../ubuntu_version.txt .
  - cp ../installed_packages.txt .
  - git add ubuntu_version.txt installed_packages.txt
  - git commit -m "Update Ubuntu version and installed packages from Travis CI"
  - git push origin main
