dist: focal  # Użyj Ubuntu 20.04

script:
  # Sprawdź wersję Ubuntu i zapisz do pliku
  - lsb_release -a > ubuntu_version.txt
  - cat ubuntu_version.txt

after_success:
  - git config --global user.name "Travis CI"
  - git config --global user.email "your-email@example.com"
  
  # Skopiuj repozytorium za pomocą tokena
  - git clone https://$GITHUB_TOKEN@github.com/username/repo.git
  - cd repo

  # Skopiuj plik i wykonaj commit
  - cp ../ubuntu_version.txt .
  - git add ubuntu_version.txt
  - git commit -m "Update Ubuntu version from Travis CI"
  
  # Wypchnij zmiany na repozytorium
  - git push origin main
